import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { X, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, BookingBand } from "@/components/AyurSite";
import exterior from "@/assets/clinic_exterior.jpeg";
import reception from "@/assets/clinic_reception.jpeg";
import loungeOne from "@/assets/clinic_lounge_1.jpeg";
import loungeTwo from "@/assets/clinic_lounge_2.jpeg";
import treatmentRoom from "@/assets/clinic_treatment_room.jpeg";
import heroPoster from "@/assets/ayur-mannoor-poster.jpg";
import heroFilm from "@/assets/ayur-mannoor-hero.webm";
import veranda from "@/assets/kerala-veranda.jpg";
import room from "@/assets/treatment-room.jpg";
import shirodhara from "@/assets/shirodhara.jpg";
import details from "@/assets/ayurveda-details.jpg";
const images = [[exterior,"Exterior of AYUR MANNOOR clinic"],[reception,"Reception at AYUR MANNOOR"],[loungeOne,"Seating area at AYUR MANNOOR"],[loungeTwo,"Clinic lounge at AYUR MANNOOR"],[treatmentRoom,"Treatment room at AYUR MANNOOR"],[details,"Ayurvedic herbs and oils — illustrative imagery"],[room,"Traditional treatment room — illustrative imagery"],[shirodhara,"Shirodhara setting — illustrative imagery"],[veranda,"Kerala veranda — illustrative imagery"],[heroPoster,"AYUR MANNOOR brand film"]] as const;
export const Route = createFileRoute("/gallery")({ head: () => ({ meta: [
  { title: "Gallery | AYUR MANNOOR Kannur" }, { name: "description", content: "Explore authentic photographs of AYUR MANNOOR's clinic in Kannur, alongside illustrative treatment imagery and the brand film." },
  { property: "og:title", content: "Gallery | AYUR MANNOOR" }, { property: "og:description", content: "Explore AYUR MANNOOR and the atmosphere of traditional Kerala Ayurveda." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Gallery });
function Gallery(){ const [selected,setSelected]=useState<number|null>(null); useEffect(()=>{ if(selected===null)return; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);if(e.key==="ArrowRight")setSelected((selected+1)%images.length);if(e.key==="ArrowLeft")setSelected((selected+images.length-1)%images.length)};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey)},[selected]); const current=selected===null?null:images[selected]; return <><PageIntro eyebrow="Gallery" title="A quiet sense of place." text="Inside AYUR MANNOOR: the clinic, its treatment room, and spaces for care in Karuvanchal, Kannur."/><section className="section pt-0"><div className="mx-auto grid max-w-[1400px] grid-cols-2 items-start gap-3 md:grid-cols-3">{images.map(([src,alt],i)=><Button key={alt} variant="ghost" onClick={()=>setSelected(i)} aria-label={`Open image: ${alt}`} className={`block h-auto w-full rounded-none p-0 ${i===0?"col-span-2 md:col-span-1 md:row-span-2":""}`}><img src={src} alt={alt} loading="lazy" className={`block w-full object-cover ${i===0?"aspect-[4/3] md:aspect-[3/4] md:h-full":"aspect-[4/3]"}`}/></Button>)}</div><p className="mx-auto mt-5 max-w-[1400px] text-xs text-muted-foreground">The first five photographs show AYUR MANNOOR. Treatment and environment photographs that follow are illustrative.</p></section><BookingBand/>{current&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-gallery-overlay p-4" role="dialog" aria-modal="true" aria-label="Gallery image"><Button variant="ghost" size="icon" aria-label="Close gallery" onClick={()=>setSelected(null)} className="absolute right-5 top-5 text-hero"><X/></Button><Button variant="ghost" size="icon" aria-label="Previous image" onClick={()=>setSelected(((selected ?? 0)+images.length-1)%images.length)} className="absolute left-3 text-hero"><ChevronLeft/></Button>{selected===images.length-1?<video key="brand-film" src={heroFilm} poster={heroPoster} autoPlay loop muted playsInline controls className="max-h-[85vh] max-w-[80vw] object-contain" aria-label="AYUR MANNOOR brand film"/>:<img src={current[0]} alt={current[1]} className="max-h-[85vh] max-w-[80vw] object-contain"/>}<Button variant="ghost" size="icon" aria-label="Next image" onClick={()=>setSelected(((selected ?? 0)+1)%images.length)} className="absolute right-3 text-hero"><ChevronRight/></Button><p className="absolute bottom-5 text-xs text-hero">{current[1]}</p></div>}</> }
