import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { X, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, BookingBand } from "@/components/AyurSite";
import doctor from "@/assets/dr-anupam-mathew.jpeg.asset.json";
import veranda from "@/assets/kerala-veranda.jpg";
import room from "@/assets/treatment-room.jpg";
import shirodhara from "@/assets/shirodhara.jpg";
import details from "@/assets/ayurveda-details.jpg";
const images = [[doctor.url,"Dr. Anupam Mathew at AYUR MANNOOR"],[details,"Ayurvedic herbs and oils — illustrative imagery"],[room,"Traditional treatment room — illustrative imagery"],[shirodhara,"Shirodhara setting — illustrative imagery"],[veranda,"Kerala veranda — illustrative imagery"]] as const;
export const Route = createFileRoute("/gallery")({ head: () => ({ meta: [
  { title: "Gallery | AYUR MANNOOR Kannur" }, { name: "description", content: "A visual look at AYUR MANNOOR and traditional Ayurveda, including Dr. Anupam Mathew and illustrative treatment imagery." },
  { property: "og:title", content: "Gallery | AYUR MANNOOR" }, { property: "og:description", content: "Explore AYUR MANNOOR and the atmosphere of traditional Kerala Ayurveda." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Gallery });
function Gallery(){ const [selected,setSelected]=useState<number|null>(null); useEffect(()=>{ if(selected===null)return; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);if(e.key==="ArrowRight")setSelected((selected+1)%images.length);if(e.key==="ArrowLeft")setSelected((selected+images.length-1)%images.length)};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey)},[selected]); const current=selected===null?null:images[selected]; return <><PageIntro eyebrow="Gallery" title="A quiet sense of place." text="A portrait from AYUR MANNOOR alongside illustrative imagery of traditional Kerala Ayurveda."/><section className="section pt-0"><div className="mx-auto grid max-w-[1400px] grid-cols-2 gap-3 md:grid-cols-3">{images.map(([src,alt],i)=><Button key={alt} variant="ghost" onClick={()=>setSelected(i)} aria-label={`Open image: ${alt}`} className={`h-auto w-full rounded-none p-0 ${i===0?"md:row-span-2":""}`}><img src={src} alt={alt} loading="lazy" className={`w-full object-cover ${i===0?"aspect-[3/4] md:h-full":"aspect-[4/3]"}`}/></Button>)}</div><p className="mx-auto mt-5 max-w-[1400px] text-xs text-muted-foreground">Treatment and environment photographs are illustrative, not photographs of the clinic.</p></section><BookingBand/>{current&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-gallery-overlay p-4" role="dialog" aria-modal="true" aria-label="Gallery image"><Button variant="ghost" size="icon" aria-label="Close gallery" onClick={()=>setSelected(null)} className="absolute right-5 top-5 text-hero"><X/></Button><Button variant="ghost" size="icon" aria-label="Previous image" onClick={()=>setSelected(((selected ?? 0)+images.length-1)%images.length)} className="absolute left-3 text-hero"><ChevronLeft/></Button><img src={current[0]} alt={current[1]} className="max-h-[85vh] max-w-[80vw] object-contain"/><Button variant="ghost" size="icon" aria-label="Next image" onClick={()=>setSelected(((selected ?? 0)+1)%images.length)} className="absolute right-3 text-hero"><ChevronRight/></Button><p className="absolute bottom-5 text-xs text-hero">{current[1]}</p></div>}</> }
